version: '3.3'

services:
  web:
    image: python:3.8
    volumes:
      - .:/code
      - urban-data-dev-libs:/python-libs
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - PYTHONUSERBASE=/python-libs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mongo:
    image: mongo
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  urban-data-dev-libs: