# Generated by Django 3.2 on 2023-03-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('build_status', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('start_month', models.IntegerField()),
                ('construction_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Tipo 0'), (1, 'Tipo 1'), (2, 'Tipo 2')], default=None, null=True)),
                ('date_diff', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_in', models.DateTimeField()),
                ('property_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Propiedad 0'), (1, 'Propiedad 1'), (2, 'Propiedad 2'), (3, 'Propiedad 3'), (4, 'Propiedad 4')], default=None, null=True)),
                ('end_week', models.IntegerField()),
                ('typology_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Tipologia 0'), (1, 'Tipologia 1'), (2, 'Tipologia 2'), (3, 'Tipologia 3'), (4, 'Tipologia 4'), (5, 'Tipologia 5'), (6, 'Tipologia 6')], default=None, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lat', models.DecimalField(decimal_places=50, max_digits=50)),
                ('lng', models.DecimalField(decimal_places=50, max_digits=50)),
                ('bondary_id', models.IntegerField()),
                ('id_uda', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('listing_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Tipo 0'), (1, 'Tipo 1')], default=None, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
