# Generated by Django 3.2 on 2023-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='lat',
            field=models.DecimalField(decimal_places=40, max_digits=42),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='lng',
            field=models.DecimalField(decimal_places=40, max_digits=42),
        ),
    ]
