# Generated by Django 3.2 on 2023-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_info', '0002_auto_20230323_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='lat',
            field=models.DecimalField(decimal_places=50, max_digits=52),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='lng',
            field=models.DecimalField(decimal_places=50, max_digits=52),
        ),
    ]
