# Generated by Django 3.2 on 2023-03-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_info', '0003_auto_20230323_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='houseinfo',
            name='lng',
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='coordinates',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
